spring:
  datasource:
    url: jdbc:mysql://localhost:3306/countries
    password: Vaporru21@
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none